[tool.poetry]
name = "amdfan"
version = "0.1.0"
description = ""
authors = ["mcgillij <mcgillivray.jason@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.20.1"
PyYAML = "^5.4.1"
rich = "^9.10.0"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
ipython = "^7.20.0"
pylint = "^2.6.0"
flake8 = "^3.8.4"
black = "^20.8b1"
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
